workflows:
  my-workflow:
    name: Build and test
    scripts:
      - echo "Building the project"
      - xcodebuild -workspace RPG34.xcworkspace -scheme RPG34 -sdk iphoneos -configuration Release archive -archivePath $HOME/build/RPG34.xcarchive
      - xcodebuild -exportArchive -archivePath $HOME/build/RPG34.xcarchive -exportOptionsPlist exportOptions.plist -exportPath $HOME/build
